In [10]:
import pandas as pd
import numpy as np


import os, wrds

os.environ["WRDS_USERNAME"] = "YOUR_WRDS_USERNAME"

db = wrds.Connection(wrds_username = os.environ["WRDS_USERNAME"])
print(" Successful")

Loading library list...
Done
 Successful

In [ ]:
# 배당성과 수익성의 관계 분석

answer = db.raw_sql("""

                    WITH div_y AS(
                    SELECT 
                        d.permno,
                        EXTRACT(YEAR FROM d.dclrdt) AS year,
                        SUM(d.divamt) AS total_div,
                        ABS(AVG(d.divamt/NULLIF(px.prc,0)))*100 AS avg_div
                    FROM crsp.dse d
                    LEFT JOIN LATERAL(
                        SELECT f.date, f.prc
                        FROM crsp.dsf f
                        WHERE d.permno = f.permno
                        AND f.date <= d.dclrdt
                        ORDER BY f.date DESC
                        LIMIT 1) px ON TRUE
                    WHERE d.permno = 14593
                    GROUP BY (d.permno, EXTRACT(YEAR FROM d.dclrdt))
                    ),
                    -- permno, 년도, 배당금, 배당률


                    fund AS(
                    SELECT 
                        f.gvkey,
                        EXTRACT(YEAR FROM f.datadate) AS year,
                        SUM(f.niq) AS total_niq,
                        AVG(f.atq) AS total_asset
                    FROM comp.fundq f
                    GROUP BY (f.gvkey, EXTRACT(YEAR FROM f.datadate))
                    ),
                    -- gvkey, 년도, 총이익, 총자산

                    fund_link AS(
                    SELECT 
                        f.gvkey,
                        f.year,
                        f.total_niq,
                        f.total_asset,
                        l.lpermno
                    FROM fund f
                    JOIN crsp.ccmxpf_linktable l
                    ON f.gvkey = l.gvkey
                    WHERE l.lpermno = 14593
                    AND l.linktype IN ('LU','LC')        -- Compustat↔CRSP 보편적 링크
                    AND l.linkprim IN ('P','C')          -- Primary / Company level
                    --ORDER BY f.year
                    --LIMIT 1
                    )
                    -- gvkey, 년도, 총이익, 총자산, permno

                    
                    -- 그러면 이제 div_y의 배당금, 배당률을 가지고 오면 됨
                    SELECT 
                        f.lpermno,
                        f.year,
                        d.total_div,
                        d.avg_div,
                        f.total_niq,
                        f.total_asset
                    FROM fund_link f
                    LEFT JOIN div_y d
                    ON d.year = f.year
                    AND d.permno = f.lpermno
                    ORDER BY f.year
                        """)

answer

    lpermno    year  total_div   avg_div  total_niq    total_asset
0   14593.0  1979.0       <NA>      <NA>      2.647         24.636
1   14593.0  1980.0       <NA>      <NA>     16.472         74.883
2   14593.0  1981.0       <NA>      <NA>     45.561       238.2775
3   14593.0  1982.0       <NA>      <NA>     71.263       348.0735
4   14593.0  1983.0       <NA>      <NA>     59.017      537.17725
5   14593.0  1984.0       <NA>      <NA>    104.332        772.396
6   14593.0  1985.0       <NA>      <NA>     72.049      926.78475
7   14593.0  1986.0       <NA>      <NA>    155.511     1151.69075
8   14593.0  1987.0       0.26  0.130459    280.391       1466.236
9   14593.0  1988.0       0.34  0.208972    419.342     1920.30675
10  14593.0  1989.0       0.41   0.24772    438.421       2569.681
11  14593.0  1990.0       0.45  0.306473    500.564     2949.54275
12  14593.0  1991.0       0.48  0.233459     325.35      3529.1745
13  14593.0  1992.0       0.48  0.216944    525.696      4195.0805
14  14593.0  1993.0       0.48  0.330048    -34.734      4862.9785
15  14593.0  1994.0       0.48  0.379072     458.16     5311.25875
16  14593.0  1995.0       0.48  0.301808      167.0         6236.5
17  14593.0  1996.0       <NA>      <NA>     -867.0        5303.75
18  14593.0  1997.0       <NA>      <NA>     -878.0        4296.75
19  14593.0  1998.0       <NA>      <NA>      414.0        4221.25
20  14593.0  1999.0       <NA>      <NA>      632.0        5675.25
21  14593.0  2000.0       <NA>      <NA>      408.0         6682.0
22  14593.0  2001.0       <NA>      <NA>      208.0         6086.0
23  14593.0  2002.0       <NA>      <NA>       19.0         6281.0
24  14593.0  2003.0       <NA>      <NA>      140.0         6647.0
25  14593.0  2004.0       <NA>      <NA>      508.0         7842.5
26  14593.0  2005.0        0.0       0.0     1598.0       11582.75
27  14593.0  2006.0       <NA>      <NA>     2428.0       16422.75
28  14593.0  2007.0       <NA>      <NA>     4073.0        23936.0
29  14593.0  2008.0       <NA>      <NA>     5508.0       36134.75
30  14593.0  2009.0       <NA>      <NA>     9358.0        48201.0
31  14593.0  2010.0       <NA>      <NA>    16639.0       70926.75
32  14593.0  2011.0       <NA>      <NA>    32982.0       114178.5
33  14593.0  2012.0        5.3  0.437873    41747.0       171495.5
34  14593.0  2013.0       11.8  0.642524    37031.0      206695.75
35  14593.0  2014.0       7.28  0.429667    44462.0       230560.5
36  14593.0  2015.0       2.03  0.418576    53731.0       279527.0
37  14593.0  2016.0       2.23  0.534489    45217.0       315926.5
38  14593.0  2017.0       2.46  0.422855    50525.0       365454.5
39  14593.0  2018.0       2.82  0.379829    59431.0      364035.75
40  14593.0  2019.0       3.04   0.38525    57527.0      335842.75
41  14593.0  2020.0      2.615  0.182472    63930.0       328921.5
42  14593.0  2021.0      0.865  0.150773   100555.0      349797.75
43  14593.0  2022.0       0.91  0.145934    95171.0      346618.25
44  14593.0  2023.0       0.95   0.13949   100913.0      343323.75
45  14593.0  2024.0       0.99  0.124519    96150.0       344522.0
46  14593.0  2025.0       <NA>      <NA>    75680.0  340656.333333

:

In [ ]:
apple_div = db.raw_sql("""
                    SELECT 
                        d.permno,
                        EXTRACT(YEAR FROM d.paydt) AS year,
                        SUM(d.divamt) AS total_div,
                        ABS(AVG(d.divamt/NULLIF(px.prc,0)))*100 AS avg_div
                    FROM crsp.dse d
                    LEFT JOIN LATERAL(
                        SELECT f.date, f.prc
                        FROM crsp.dsf f
                        WHERE d.permno = f.permno
                        AND f.date >= d.paydt
                        ORDER BY f.date
                        LIMIT 1) px ON TRUE
                    WHERE d.permno = 14593
                    GROUP BY (d.permno, EXTRACT(YEAR FROM d.paydt))
""")
apple_div

    permno    year  total_div    avg_div
0    14593  1987.0       0.26   0.225597
1    14593  1988.0       0.34   0.295011
2    14593  1989.0       0.41   0.355748
3    14593  1990.0       0.45   0.390456
4    14593  1991.0       0.48   0.416486
5    14593  1992.0       0.48   0.416486
6    14593  1993.0       0.48   0.416486
7    14593  1994.0       0.48   0.416486
8    14593  1995.0       0.48   0.416486
9    14593  2000.0        0.0        0.0
10   14593  2005.0        0.0        0.0
11   14593  2012.0        5.3   9.197397
12   14593  2013.0       11.8  10.238612
13   14593  2014.0       7.28   5.053362
14   14593  2015.0       2.03   1.761388
15   14593  2016.0       2.23   1.934924
16   14593  2017.0       2.46    2.13449
17   14593  2018.0       2.82   2.446855
18   14593  2019.0       3.04   2.637744
19   14593  2020.0      2.615   1.815184
20   14593  2021.0      0.865   0.750542
21   14593  2022.0       0.91   0.789588
22   14593  2023.0       0.95   0.824295
23   14593  2024.0       0.99   0.859002
24   14593    <NA>       <NA>       <NA>